print("Hello there")
print("I would like to know ,what´s your favorite color?")
color=input("Could you write your favorite color please: ")
print("Great!, your favorite color is: ",color)
print("Do you have another favorite color?")
print("If your answer is 'YES', please type your second color below, but if your answer is 'NO', please type NO")
color2=input("Write now: ")
print("Your answer is: ",color2)
print("Thanks for your time, bye")